version: '3.5'

services:
  fc.codeflix.catalog.fb:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:  
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: C0D3fl1X.@
        MYSQL_DATABASE: catalog
networks:
    default:
        name: service_catalog